name:         uniform-error
version:      0.1.3.2
license:      GPL-2.0-only
# license-file: GPL_3
maintainer:   Andrew U. Frank <uniform@gerastree.at>
bug-reports:  https://github.com/andrewufrank/uniform-error/issues
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category: Error Exception Uniform
synopsis: Handling errors in the uniform framework
description: |
  A minimal package to handle errors and exception
  in a simple but flexible way. Includes functions to adapt the prefered method of calling IO with error handling (ErrIO) to the 
  approaches encountered in other packages when writing applications.

  Please see the README on GitHub at <https://github.com/andrewufrank/uniform-error/readme>


extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
# - monads-tf
- transformers
- safe
- uniform-strings >= 0.1.3
- data-default

library:
  source-dirs: 
  - .
  verbatim:
    autogen-modules:
        Paths_uniform_error

tests:
  error-test:
    main:                Testing.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uniform-error
    - HTF
